### ISSUE TITLE
Attempting to run jar

### ISSUE THREAD

**Issue by adamgpeterson** [dsyer/spring-boot-sample-data-eclipselink#1]
Any suggestion on executing as standalone jar?

encountered during context initialization - cancelling refresh attempt

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory'
defined in sample.data.jpa.SampleDataJpaApplication: Invocation of init method failed; nested exception is jav
a.lang.IllegalStateException: Cannot apply class transformer without LoadTimeWeaver specified
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(Abstrac
tAutowireCapableBeanFactory.java:1566)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractA
utowireCapableBeanFactory.java:539)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAut
owireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:
302)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingleto
nBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:29
8)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)

```
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.j
```

ava:956)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(Abst
ractApplicationContext.java:747)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.j
ava:480)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicat
ionContext.java:109)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
        at sample.data.jpa.SampleDataJpaApplication.main(SampleDataJpaApplication.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Cannot apply class transformer without LoadTimeWeaver specified
        at org.springframework.orm.jpa.persistenceunit.SpringPersistenceUnitInfo.addTransformer(SpringPersiste
nceUnitInfo.java:80)
        at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProv
ider.java:348)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory
(LocalContainerEntityManagerFactoryBean.java:343)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManag
erFactoryBean.java:318)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(Abst
ractAutowireCapableBeanFactory.java:1625)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(Abstrac
tAutowireCapableBeanFactory.java:1562)
        ... 21 common frames omitted

**Comment by kjozsa** [comment]
Hi,

I'm fighting the exact same problem on my local project and I see it also happens with this sample. Attempting to run the project with java -jar target/*.jar fails with "IllegalStateException: Cannot apply class transformer without LoadTimeWeaver specified" - clearly, the LTW agent required by Eclipselink does not get started this way.

Do you know a fix or any suggested workaround for this problem?

**Comment by adamgpeterson** [comment]
Sorry, I never figured it out and have not heard anything. I did notice a recent modification to the project. May it's fixed? 

```
 On Tuesday, May 5, 2015 10:11 AM, Kristof Jozsa <notifications@github.com> wrote:
```

 Hi,I'm fighting the exact same problem on my local project and I see it also happens with this sample. Attempting to run the project with java -jar target/*.jar fails with "IllegalStateException: Cannot apply class transformer without LoadTimeWeaver specified" - clearly, the LTW agent required by Eclipselink does not get started this way.Do you know a fix or any suggested workaround for this problem? —

**Comment by kjozsa** [comment]
You can specify the required javaagent with java
-javaagent:/full/path/to/spring-instrument.jar -jar app.jar but it won't
work otherwise.

I found a spring-boot ticket about the issue and the maintainer claims it
behaves exactly how it should - I doubt that :)

**Comment by igormukhin** [comment]
Alternatively you can use static weaving. Example configuration: https://github.com/igormukhin/spring-boot-sample-data-eclipselink-war . See pom.xml and JpaConfiguration.detectWeavingMode()

**Comment by dsyer** [comment]
OK. So it works as designed. I'll add a section to the README on how to attach the agent.
